SELECT NOMBRES, APELLIDOS FROM ESTUDIANTE;

SELECT NOMBRE_OPCION_GRADO, DURACION_ESTIMADA_PERIODOS FROM OPCION_GRADO;

SELECT E.NOMBRES || ' ' || E.APELLIDOS "NOMBRES Y APELLIDOS", P.NOMBRE_PROGRAMA
FROM ESTUDIANTE E
JOIN PROGRAMA_ACADEMICO p ON E.ID_PROGRAMA_ACADEMICO  = P.ID_PROGRAMA_ACADEMICO 

SELECT E.NOMBRES || ' ' || E.APELLIDOS "NOMBRES Y APELLIDOS", TG.TITULO_GRADO "TITULO DE GRADO", TG.ID_ESTADO_TG "ESTADO DE TRABAJO DE GRADO", TG.ID_OPCION_GRADO "OPCIÓN DE GRADO"
FROM ESTUDIANTE E, TRABAJO_GRADO TG
JOIN EST_TRBJO_GRA ETG ON ETG.ID_TRABAJO_GRADO  = TG.ID_TRABAJO_GRADO 

SELECT TG.TITULO_GRADO, ET.NOMBRE_ESTADO, OG.NOMBRE_OPCION_GRADO
FROM TRABAJO_GRADO TG
JOIN ESTADO_TRABAJO_GRADO ET ON TG.ID_ESTADO_TG = ET.ID_ESTADO_TG
JOIN OPCION_GRADO OG ON TG.ID_OPCION_GRADO = OG.ID_OPCION_GRADO;

SELECT D.NOMBRES_DOCENTE || ' ' || D.APELLIDOS_DOCENTE  "NOMBRES Y APELLIDOS", ASGJ.CONCEPTO_EMITIDO "CONCEPTO EMITIDO"
FROM DOCENTE D
JOIN ASIGNACION_JURADO ASGJ ON ASGJ.ID_DOCENTE = D.ID_DOCENTE

SELECT D.NOMBRES_DOCENTE, D.APELLIDOS_DOCENTE, AJ.CONCEPTO_EMITIDO
FROM ASIGNACION_JURADO AJ
JOIN DOCENTE D ON AJ.ID_DOCENTE = D.ID_DOCENTE;

SELECT E.NOMBRES "NOMBRE ESTUDIANTES", P.NOMBRE_PROGRAMA "PROGRAMA", COUNT(E.ID_ESTUDIANTE) "TOTAL ESTUDIANTES"
FROM ESTUDIANTE E
LEFT JOIN PROGRAMA_ACADEMICO P
ON P.ID_PROGRAMA_ACADEMICO = E.ID_PROGRAMA_ACADEMICO
GROUP BY E.NOMBRES, P.NOMBRE_PROGRAMA

SELECT P.NOMBRE_PROGRAMA, COUNT(E.ID_ESTUDIANTE) AS TOTAL_ESTUDIANTES
FROM PROGRAMA_ACADEMICO P
LEFT JOIN ESTUDIANTE E ON P.ID_PROGRAMA_ACADEMICO = E.ID_PROGRAMA_ACADEMICO
GROUP BY P.NOMBRE_PROGRAMA;

SELECT TITULO_GRADO, CALIFICACION_FINAL
FROM TRABAJO_GRADO
WHERE TRABAJO_GRADO.CALIFICACION_FINAL > 4.5

SELECT E.NOMBRES "NOMBRE ESTUDIANTE", TG.MENCION_HONORIFICA "MENCION HONORIFICA"
FROM ESTUDIANTE E, TRABAJO_GRADO TG 
JOIN EST_TRBJO_GRA ETG ON TG.ID_TRABAJO_GRADO = ETG.ID_TRABAJO_GRADO
WHERE TG.MENCION_HONORIFICA = 'Meritorio'

SELECT EMP.NOMBRE_EMPRESA
FROM EMPRESA EMP
LEFT JOIN CONVENIO CNV
ON CNV.ID_EMPRESA = EMP.ID_EMPRESA
WHERE SYSDATE BETWEEN CNV.FECHA_INICIO_VIGENCIA AND CNV.FECHA_FIN_VIGENCIA

SELECT TG.TITULO_GRADO "NOMBRE TRABAJO DE GRADO", TG.CALIFICACION_FINAL
FROM TRABAJO_GRADO TG
WHERE TG.CALIFICACION_FINAL = 0 

SELECT DOC.NOMBRES_DOCENTE , TG.TITULO_GRADO
FROM TRABAJO_GRADO TG
LEFT JOIN ASIGNACION_ASESOR AA 
ON AA.ID_TRABAJO_GRADO = TG.ID_TRABAJO_GRADO
JOIN DOCENTE DOC
ON DOC.ID_DOCENTE = AA.ID_DOCENTE
WHERE AA.TIPO_ASESOR = 'Principal';

SELECT TG.TITULO_GRADO, D.NOMBRES_DOCENTE, D.APELLIDOS_DOCENTE
FROM TRABAJO_GRADO TG
JOIN ASIGNACION_ASESOR AA ON TG.ID_TRABAJO_GRADO = AA.ID_TRABAJO_GRADO
JOIN DOCENTE D ON AA.ID_DOCENTE = D.ID_DOCENTE
WHERE AA.TIPO_ASESOR = 'Principal';


