SELECT EMP_CARGO, AVG(EMP_SALARIO) AS PROMEDIO
FROM EMPLEADOS
GROUP BY EMP_CARGO
HAVING AVG(EMP_SALARIO) > 1200000;

SELECT MIN(E.EMP_FECHACONTRATO)AS CONTRATOMIN, MAX(E.EMP_FECHACONTRATO)AS CONTRATOMAX 
FROM EMPLEADOS E;

SELECT MIN(E.EMP_NOMBRE) AS "NOMBRE MINIMO ORDENADO POR ORDEN ALFABETICO", 
       MAX(E.EMP_NOMBRE) AS "NOMBRE MAXIMO ORDENADO POR ORDEN ALFABETICO"
FROM EMPLEADOS E;

SELECT MIN(E.EMP_FECHACONTRATO) AS "FECHA CONTRATO MINIMA",
       MAX(E.EMP_FECHACONTRATO) AS "FECHA CONTRATO MAXIMA"
FROM EMPLEADOS E;

--ROUND REDONDEA EL VALOR DECIMAL Y SE PONE UN ,n PARA LA CANTIDAD DE DECIMALES
SELECT SUM(E.EMP_SALARIO) AS "SUMA DE LOS SALARIOS", ROUND(AVG(E.EMP_SALARIO),2) AS "PROMEDIO DE LOS SALARIOS",
       MIN(E.EMP_SALARIO) AS "SALARIO MINIMO", MAX(E.EMP_SALARIO) AS "SALARIO MAXIMO"
FROM EMPLEADOS E;

SELECT COUNT(*)
FROM EMPLEADOS;

SELECT COUNT(*)
FROM EMPLEADOS
WHERE DEP_ID = 30;

-- CUANTOS DEPARTAMENTOS HAY EN LA TABLA EMPLEADOS
SELECT COUNT(DEP_ID)
FROM EMPLEADOS;

--CONTAR FILAS SIN REPETICIONES -- DISTINCT --
SELECT COUNT(DISTINCT DEP_ID)
FROM EMPLEADOS;

SELECT COUNT(*)
FROM EMPLEADOS;

SELECT COUNT(EMP_COMISION)
FROM EMPLEADOS;

--PONE VALORES NULOS EN 0, PERO SOLO EN LA CONSULTA
SELECT COUNT(NVL(EMP_COMISION,0))
FROM EMPLEADOS;

SELECT DEP_ID, COUNT(*)
FROM EMPLEADOS
GROUP BY DEP_ID
ORDER BY DEP_ID ASC;

SELECT COUNT(DISTINCT(EMP_JEFE))AS NUMERO_JEFES
FROM EMPLEADOS;

SELECT DEP_ID, EMP_CARGO, SUM(EMP_SALARIO)
FROM EMPLEADOS
GROUP BY DEP_ID, EMP_CARGO;

SELECT MAX(EMP_NOMBRE) AS EMPLEADO 
FROM EMPLEADOS
WHERE EMP_FECHACONTRATO IN(BETWEEN(31-DEC-2000 AND 31-DEC-2004));

SELECT EXTRACT(YEAR FROM EMP_FECHACONTRATO) AS AÑO_CONTRATADO, COUNT(DISTINCT EMP_FECHACONTRATO) AS CANTIDAD
FROM EMPLEADOS
WHERE EXTRACT(YEAR FROM EMP_FECHACONTRATO) IN (2001,2002,2003,2004)
GROUP BY EMP_FECHACONTRATO
ORDER BY EMP_FECHACONTRATO ASC;

SELECT DISTINCT EXTRACT(YEAR FROM EMP_FECHACONTRATO) AS AÑO_CONTRATADO, COUNT(*) AS CANTIDAD
FROM EMPLEADOS
WHERE EXTRACT(YEAR FROM EMP_FECHACONTRATO) IN (2001,2002,2003,2004)
GROUP BY EXTRACT(YEAR FROM EMP_FECHACONTRATO);

SELECT DEP_ID, SUM(EMP_SALARIO)
FROM EMPLEADOS
GROUP BY DEP_ID
HAVING SUM(EMP_SALARIO)>10000000;

