SELECT EMPLEADOS.EMP_NOMBRE, DEPARTAMENTOS.DEP_NOMBRE
FROM   EMPLEADOS, DEPARTAMENTOS;

SELECT EMPLEADOS.EMP_ID, EMPLEADOS.EMP_NOMBRE,
       EMPLEADOS.DEP_ID, DEPARTAMENTOS.DEP_ID,
       DEPARTAMENTOS.DEP_NOMBRE
FROM   EMPLEADOS, DEPARTAMENTOS
WHERE  EMPLEADOS.DEP_ID = DEPARTAMENTOS.DEP_ID;

SELECT EMPLEADOS.EMP_ID, EMPLEADOS.EMP_NOMBRE,
       EMPLEADOS.DEP_ID, DEPARTAMENTOS.DEP_ID,
       DEPARTAMENTOS.DEP_NOMBRE
FROM   EMPLEADOS, DEPARTAMENTOS
WHERE  EMPLEADOS.DEP_ID = DEPARTAMENTOS.DEP_ID 
AND    EMPLEADOS.EMP_NOMBRE = 'LOPEZ';

SELECT  C.CLI_NOMBRE, E.EMP_NOMBRE, D.DEP_NOMBRE
FROM    CLIENTES C, EMPLEADOS E, DEPARTAMENTOS D
WHERE   C.EMP_ID = E.EMP_ID 
AND     E.DEP_ID = D.DEP_ID;

SELECT E.EMP_NOMBRE, E.EMP_SALARIO, G.GRA_ID
FROM EMPLEADOS E, GRADOSDESALARIO G
WHERE E.EMP_SALARIO BETWEEN G.GRA_LIMITEINFERIOR
                    AND G.GRA_LIMITESUPERIOR;


SELECT E.EMP_NOMBRE, D.DEP_NOMBRE
FROM EMPLEADOS E, DEPARTAMENTOS D
WHERE E.DEP_ID(+) = D.DEP_ID
ORDER BY D.DEP_NOMBRE, E.EMP_NOMBRE;

SELECT JEFES.EMP_NOMBRE || ' ES JEFE DE '
       || SUB.EMP_NOMBRE AS "RELACION"
FROM   EMPLEADOS SUB, EMPLEADOS JEFES
WHERE  JEFES.EMP_ID = SUB.EMP_JEFE;


